### PR TITLE
Shcaml's new version for ocaml >=4.02

### PR DESCRIPTION
**Pull request by Armael**
For review by @tov .

A few things still need to be done before merging:
- What should be the version number of the new version?
- What should be its codename?
- Should I rebase and squash the commits a bit more?
- I changed the CSS of the documentation and tweaked it a bit, do you like it? (preview here http://armael.github.io/shcaml-zero/dev/ )
- It would be good to update this page http://users.eecs.northwestern.edu/~jesse/code/shcaml/ at some point

### CODE REVIEW

**Comment by tov** [comment]
That sounds good to me. The docs look nice. I think we should bump the version to 0.2.0. There's a list of future codenames somewhere—have you seen it?

**Comment by Armael** [comment]
Yes, It's now in `pkg/config.ml`

**Comment by tov** [comment]
Cool. So is this ready to be merged, or is there more you want to do? I’ll update the website once a release is ready, I guess.

**Comment by samoht** [comment]
sorry to hijack the discussion but you could rename "Objective Caml" into "OCaml" in the (nicely) looking docs? Thanks!

**Comment by Armael** [comment]
This is now ready to be merged!

**Comment by tov** [comment]
Done. Thanks!

**Pull request merged**
