### PR TITLE
Prepare for release of shcaml 0.2.0

### PR DESCRIPTION
**Pull request by Armael**
Hi,

It's been a while, but I finally took some time to finish preparing the new release! The commits attached mainly fiddle with the build system, the documentation setup and all that. Once this is merged, I'll tag the release and publish it on opam.

Preview of the documentation: https://armael.github.io/shcaml/doc

@tov: Regarding the documentation location: it would be a bit simpler if it were hosted using github-pages, because `topkg` (that I use for publishing the package) can automatically upload the generated docs there. As indicated in the README, the docs url would be https://tov.github.io/shcaml/doc . If that's fine, then could you setup a redirection from http://users.eecs.northwestern.edu/~jesse/code/shcaml/doc/ to the new docs location?

Cheers,
Armael

### CODE REVIEW

**Comment by tov** [comment]
Awesome! I like what you've done with Line.

Yes, I'd be happy to add the redirect, once the target of the redirect exists. Do I need to do something to make it exist?

**Comment by Armael** [comment]
I just need to merge the PR and tag the release before generating the docs. I'll do that now, and then the docs should exist at the new location.

**Comment by tov** [comment]
Okay, I've added the redirect. Should I also get rid of the page at http://users.eecs.northwestern.edu/~jesse/code/shcaml/ and link to GitHub instead, do you think?

**Comment by Armael** [comment]
Hop, [docs are online](https://tov.github.io/shcaml/doc/)!
Yes, I think you can just replace the old page with a link to the github repo.

**Comment by Armael** [comment]
Submitted on opam: https://github.com/ocaml/opam-repository/pull/8880

**Pull request merged**
